<?php

namespace Clm\PrayerRequestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrayerRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrayerRequestRepository extends EntityRepository
{
}