<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120323164911 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Album (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, release_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Contributor (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Genre (id INT AUTO_INCREMENT NOT NULL, genre VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_42911CFC835033F8 (genre), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Track (id INT AUTO_INCREMENT NOT NULL, album_id INT DEFAULT NULL, length NUMERIC(25, 5) NOT NULL, asin VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, year INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, play_count INT NOT NULL, last_played_at DATETIME DEFAULT NULL, INDEX IDX_1722D7A21137ABCF (album_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE track_artist (track_id INT NOT NULL, artist_id INT NOT NULL, INDEX IDX_499B576E5ED23C43 (track_id), INDEX IDX_499B576EB7970CF8 (artist_id), PRIMARY KEY(track_id, artist_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE track_composer (track_id INT NOT NULL, composer_id INT NOT NULL, INDEX IDX_FBACF4995ED23C43 (track_id), INDEX IDX_FBACF4997A8D2620 (composer_id), PRIMARY KEY(track_id, composer_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE track_genre (track_id INT NOT NULL, genre_id INT NOT NULL, INDEX IDX_F3A7915F5ED23C43 (track_id), INDEX IDX_F3A7915F4296D31F (genre_id), PRIMARY KEY(track_id, genre_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Track ADD CONSTRAINT FK_1722D7A21137ABCF FOREIGN KEY (album_id) REFERENCES Album(id)");
        $this->addSql("ALTER TABLE track_artist ADD CONSTRAINT FK_499B576E5ED23C43 FOREIGN KEY (track_id) REFERENCES Track(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE track_artist ADD CONSTRAINT FK_499B576EB7970CF8 FOREIGN KEY (artist_id) REFERENCES Contributor(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE track_composer ADD CONSTRAINT FK_FBACF4995ED23C43 FOREIGN KEY (track_id) REFERENCES Track(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE track_composer ADD CONSTRAINT FK_FBACF4997A8D2620 FOREIGN KEY (composer_id) REFERENCES Contributor(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE track_genre ADD CONSTRAINT FK_F3A7915F5ED23C43 FOREIGN KEY (track_id) REFERENCES Track(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE track_genre ADD CONSTRAINT FK_F3A7915F4296D31F FOREIGN KEY (genre_id) REFERENCES Genre(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Track DROP FOREIGN KEY FK_1722D7A21137ABCF");
        $this->addSql("ALTER TABLE track_artist DROP FOREIGN KEY FK_499B576EB7970CF8");
        $this->addSql("ALTER TABLE track_composer DROP FOREIGN KEY FK_FBACF4997A8D2620");
        $this->addSql("ALTER TABLE track_genre DROP FOREIGN KEY FK_F3A7915F4296D31F");
        $this->addSql("ALTER TABLE track_artist DROP FOREIGN KEY FK_499B576E5ED23C43");
        $this->addSql("ALTER TABLE track_composer DROP FOREIGN KEY FK_FBACF4995ED23C43");
        $this->addSql("ALTER TABLE track_genre DROP FOREIGN KEY FK_F3A7915F5ED23C43");
        $this->addSql("DROP TABLE Album");
        $this->addSql("DROP TABLE Contributor");
        $this->addSql("DROP TABLE Genre");
        $this->addSql("DROP TABLE Track");
        $this->addSql("DROP TABLE track_artist");
        $this->addSql("DROP TABLE track_composer");
        $this->addSql("DROP TABLE track_genre");
    }
}
